// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executedsuperstepworkerinfo.proto

package com.unipg.givip.common.protoutils;

public final class ExecutedSuperstepWorkerInfoProto {
  private ExecutedSuperstepWorkerInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExecSuperstepWorkerInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 worker = 1;
    /**
     * <code>required int32 worker = 1;</code>
     */
    boolean hasWorker();
    /**
     * <code>required int32 worker = 1;</code>
     */
    int getWorker();

    // repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    java.util.List<com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo> 
        getSuperstepInfoList();
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo getSuperstepInfo(int index);
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    int getSuperstepInfoCount();
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    java.util.List<? extends com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder> 
        getSuperstepInfoOrBuilderList();
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder getSuperstepInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Protobuf.ExecSuperstepWorkerInfo}
   */
  public static final class ExecSuperstepWorkerInfo extends
      com.google.protobuf.GeneratedMessage
      implements ExecSuperstepWorkerInfoOrBuilder {
    // Use ExecSuperstepWorkerInfo.newBuilder() to construct.
    private ExecSuperstepWorkerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExecSuperstepWorkerInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExecSuperstepWorkerInfo defaultInstance;
    public static ExecSuperstepWorkerInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ExecSuperstepWorkerInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExecSuperstepWorkerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              worker_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                superstepInfo_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              superstepInfo_.add(input.readMessage(com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          superstepInfo_ = java.util.Collections.unmodifiableList(superstepInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.class, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ExecSuperstepWorkerInfo> PARSER =
        new com.google.protobuf.AbstractParser<ExecSuperstepWorkerInfo>() {
      public ExecSuperstepWorkerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecSuperstepWorkerInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExecSuperstepWorkerInfo> getParserForType() {
      return PARSER;
    }

    public interface SuperstepInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string computationName = 1 [default = "UNKNOWN"];
      /**
       * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
       */
      boolean hasComputationName();
      /**
       * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
       */
      java.lang.String getComputationName();
      /**
       * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
       */
      com.google.protobuf.ByteString
          getComputationNameBytes();

      // required sint64 superstepIndex = 2;
      /**
       * <code>required sint64 superstepIndex = 2;</code>
       */
      boolean hasSuperstepIndex();
      /**
       * <code>required sint64 superstepIndex = 2;</code>
       */
      long getSuperstepIndex();

      // required double computationSecs = 3;
      /**
       * <code>required double computationSecs = 3;</code>
       */
      boolean hasComputationSecs();
      /**
       * <code>required double computationSecs = 3;</code>
       */
      double getComputationSecs();

      // optional double gcLengthMillis = 4;
      /**
       * <code>optional double gcLengthMillis = 4;</code>
       */
      boolean hasGcLengthMillis();
      /**
       * <code>optional double gcLengthMillis = 4;</code>
       */
      double getGcLengthMillis();

      // optional double waitingTimeMillis = 5;
      /**
       * <code>optional double waitingTimeMillis = 5;</code>
       */
      boolean hasWaitingTimeMillis();
      /**
       * <code>optional double waitingTimeMillis = 5;</code>
       */
      double getWaitingTimeMillis();

      // optional sint64 processedVertices = 6;
      /**
       * <code>optional sint64 processedVertices = 6;</code>
       */
      boolean hasProcessedVertices();
      /**
       * <code>optional sint64 processedVertices = 6;</code>
       */
      long getProcessedVertices();

      // optional sint64 nOfPartitions = 7;
      /**
       * <code>optional sint64 nOfPartitions = 7;</code>
       */
      boolean hasNOfPartitions();
      /**
       * <code>optional sint64 nOfPartitions = 7;</code>
       */
      long getNOfPartitions();
    }
    /**
     * Protobuf type {@code Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo}
     */
    public static final class SuperstepInfo extends
        com.google.protobuf.GeneratedMessage
        implements SuperstepInfoOrBuilder {
      // Use SuperstepInfo.newBuilder() to construct.
      private SuperstepInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private SuperstepInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final SuperstepInfo defaultInstance;
      public static SuperstepInfo getDefaultInstance() {
        return defaultInstance;
      }

      public SuperstepInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private SuperstepInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                computationName_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                superstepIndex_ = input.readSInt64();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                computationSecs_ = input.readDouble();
                break;
              }
              case 33: {
                bitField0_ |= 0x00000008;
                gcLengthMillis_ = input.readDouble();
                break;
              }
              case 41: {
                bitField0_ |= 0x00000010;
                waitingTimeMillis_ = input.readDouble();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                processedVertices_ = input.readSInt64();
                break;
              }
              case 56: {
                bitField0_ |= 0x00000040;
                nOfPartitions_ = input.readSInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.class, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<SuperstepInfo> PARSER =
          new com.google.protobuf.AbstractParser<SuperstepInfo>() {
        public SuperstepInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SuperstepInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<SuperstepInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string computationName = 1 [default = "UNKNOWN"];
      public static final int COMPUTATIONNAME_FIELD_NUMBER = 1;
      private java.lang.Object computationName_;
      /**
       * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
       */
      public boolean hasComputationName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
       */
      public java.lang.String getComputationName() {
        java.lang.Object ref = computationName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            computationName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
       */
      public com.google.protobuf.ByteString
          getComputationNameBytes() {
        java.lang.Object ref = computationName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          computationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required sint64 superstepIndex = 2;
      public static final int SUPERSTEPINDEX_FIELD_NUMBER = 2;
      private long superstepIndex_;
      /**
       * <code>required sint64 superstepIndex = 2;</code>
       */
      public boolean hasSuperstepIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required sint64 superstepIndex = 2;</code>
       */
      public long getSuperstepIndex() {
        return superstepIndex_;
      }

      // required double computationSecs = 3;
      public static final int COMPUTATIONSECS_FIELD_NUMBER = 3;
      private double computationSecs_;
      /**
       * <code>required double computationSecs = 3;</code>
       */
      public boolean hasComputationSecs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double computationSecs = 3;</code>
       */
      public double getComputationSecs() {
        return computationSecs_;
      }

      // optional double gcLengthMillis = 4;
      public static final int GCLENGTHMILLIS_FIELD_NUMBER = 4;
      private double gcLengthMillis_;
      /**
       * <code>optional double gcLengthMillis = 4;</code>
       */
      public boolean hasGcLengthMillis() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double gcLengthMillis = 4;</code>
       */
      public double getGcLengthMillis() {
        return gcLengthMillis_;
      }

      // optional double waitingTimeMillis = 5;
      public static final int WAITINGTIMEMILLIS_FIELD_NUMBER = 5;
      private double waitingTimeMillis_;
      /**
       * <code>optional double waitingTimeMillis = 5;</code>
       */
      public boolean hasWaitingTimeMillis() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double waitingTimeMillis = 5;</code>
       */
      public double getWaitingTimeMillis() {
        return waitingTimeMillis_;
      }

      // optional sint64 processedVertices = 6;
      public static final int PROCESSEDVERTICES_FIELD_NUMBER = 6;
      private long processedVertices_;
      /**
       * <code>optional sint64 processedVertices = 6;</code>
       */
      public boolean hasProcessedVertices() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional sint64 processedVertices = 6;</code>
       */
      public long getProcessedVertices() {
        return processedVertices_;
      }

      // optional sint64 nOfPartitions = 7;
      public static final int NOFPARTITIONS_FIELD_NUMBER = 7;
      private long nOfPartitions_;
      /**
       * <code>optional sint64 nOfPartitions = 7;</code>
       */
      public boolean hasNOfPartitions() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional sint64 nOfPartitions = 7;</code>
       */
      public long getNOfPartitions() {
        return nOfPartitions_;
      }

      private void initFields() {
        computationName_ = "UNKNOWN";
        superstepIndex_ = 0L;
        computationSecs_ = 0D;
        gcLengthMillis_ = 0D;
        waitingTimeMillis_ = 0D;
        processedVertices_ = 0L;
        nOfPartitions_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasSuperstepIndex()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasComputationSecs()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getComputationNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeSInt64(2, superstepIndex_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, computationSecs_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeDouble(4, gcLengthMillis_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeDouble(5, waitingTimeMillis_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeSInt64(6, processedVertices_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeSInt64(7, nOfPartitions_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getComputationNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt64Size(2, superstepIndex_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, computationSecs_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, gcLengthMillis_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(5, waitingTimeMillis_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt64Size(6, processedVertices_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt64Size(7, nOfPartitions_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.class, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder.class);
        }

        // Construct using com.unipg.profiler.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          computationName_ = "UNKNOWN";
          bitField0_ = (bitField0_ & ~0x00000001);
          superstepIndex_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          computationSecs_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          gcLengthMillis_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000008);
          waitingTimeMillis_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000010);
          processedVertices_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000020);
          nOfPartitions_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_descriptor;
        }

        public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo getDefaultInstanceForType() {
          return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.getDefaultInstance();
        }

        public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo build() {
          com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo buildPartial() {
          com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo result = new com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.computationName_ = computationName_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.superstepIndex_ = superstepIndex_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.computationSecs_ = computationSecs_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.gcLengthMillis_ = gcLengthMillis_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.waitingTimeMillis_ = waitingTimeMillis_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.processedVertices_ = processedVertices_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.nOfPartitions_ = nOfPartitions_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo) {
            return mergeFrom((com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo other) {
          if (other == com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.getDefaultInstance()) return this;
          if (other.hasComputationName()) {
            bitField0_ |= 0x00000001;
            computationName_ = other.computationName_;
            onChanged();
          }
          if (other.hasSuperstepIndex()) {
            setSuperstepIndex(other.getSuperstepIndex());
          }
          if (other.hasComputationSecs()) {
            setComputationSecs(other.getComputationSecs());
          }
          if (other.hasGcLengthMillis()) {
            setGcLengthMillis(other.getGcLengthMillis());
          }
          if (other.hasWaitingTimeMillis()) {
            setWaitingTimeMillis(other.getWaitingTimeMillis());
          }
          if (other.hasProcessedVertices()) {
            setProcessedVertices(other.getProcessedVertices());
          }
          if (other.hasNOfPartitions()) {
            setNOfPartitions(other.getNOfPartitions());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasSuperstepIndex()) {
            
            return false;
          }
          if (!hasComputationSecs()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string computationName = 1 [default = "UNKNOWN"];
        private java.lang.Object computationName_ = "UNKNOWN";
        /**
         * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
         */
        public boolean hasComputationName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
         */
        public java.lang.String getComputationName() {
          java.lang.Object ref = computationName_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            computationName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
         */
        public com.google.protobuf.ByteString
            getComputationNameBytes() {
          java.lang.Object ref = computationName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            computationName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
         */
        public Builder setComputationName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          computationName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
         */
        public Builder clearComputationName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          computationName_ = getDefaultInstance().getComputationName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string computationName = 1 [default = "UNKNOWN"];</code>
         */
        public Builder setComputationNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          computationName_ = value;
          onChanged();
          return this;
        }

        // required sint64 superstepIndex = 2;
        private long superstepIndex_ ;
        /**
         * <code>required sint64 superstepIndex = 2;</code>
         */
        public boolean hasSuperstepIndex() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required sint64 superstepIndex = 2;</code>
         */
        public long getSuperstepIndex() {
          return superstepIndex_;
        }
        /**
         * <code>required sint64 superstepIndex = 2;</code>
         */
        public Builder setSuperstepIndex(long value) {
          bitField0_ |= 0x00000002;
          superstepIndex_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required sint64 superstepIndex = 2;</code>
         */
        public Builder clearSuperstepIndex() {
          bitField0_ = (bitField0_ & ~0x00000002);
          superstepIndex_ = 0L;
          onChanged();
          return this;
        }

        // required double computationSecs = 3;
        private double computationSecs_ ;
        /**
         * <code>required double computationSecs = 3;</code>
         */
        public boolean hasComputationSecs() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required double computationSecs = 3;</code>
         */
        public double getComputationSecs() {
          return computationSecs_;
        }
        /**
         * <code>required double computationSecs = 3;</code>
         */
        public Builder setComputationSecs(double value) {
          bitField0_ |= 0x00000004;
          computationSecs_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double computationSecs = 3;</code>
         */
        public Builder clearComputationSecs() {
          bitField0_ = (bitField0_ & ~0x00000004);
          computationSecs_ = 0D;
          onChanged();
          return this;
        }

        // optional double gcLengthMillis = 4;
        private double gcLengthMillis_ ;
        /**
         * <code>optional double gcLengthMillis = 4;</code>
         */
        public boolean hasGcLengthMillis() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional double gcLengthMillis = 4;</code>
         */
        public double getGcLengthMillis() {
          return gcLengthMillis_;
        }
        /**
         * <code>optional double gcLengthMillis = 4;</code>
         */
        public Builder setGcLengthMillis(double value) {
          bitField0_ |= 0x00000008;
          gcLengthMillis_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double gcLengthMillis = 4;</code>
         */
        public Builder clearGcLengthMillis() {
          bitField0_ = (bitField0_ & ~0x00000008);
          gcLengthMillis_ = 0D;
          onChanged();
          return this;
        }

        // optional double waitingTimeMillis = 5;
        private double waitingTimeMillis_ ;
        /**
         * <code>optional double waitingTimeMillis = 5;</code>
         */
        public boolean hasWaitingTimeMillis() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional double waitingTimeMillis = 5;</code>
         */
        public double getWaitingTimeMillis() {
          return waitingTimeMillis_;
        }
        /**
         * <code>optional double waitingTimeMillis = 5;</code>
         */
        public Builder setWaitingTimeMillis(double value) {
          bitField0_ |= 0x00000010;
          waitingTimeMillis_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double waitingTimeMillis = 5;</code>
         */
        public Builder clearWaitingTimeMillis() {
          bitField0_ = (bitField0_ & ~0x00000010);
          waitingTimeMillis_ = 0D;
          onChanged();
          return this;
        }

        // optional sint64 processedVertices = 6;
        private long processedVertices_ ;
        /**
         * <code>optional sint64 processedVertices = 6;</code>
         */
        public boolean hasProcessedVertices() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional sint64 processedVertices = 6;</code>
         */
        public long getProcessedVertices() {
          return processedVertices_;
        }
        /**
         * <code>optional sint64 processedVertices = 6;</code>
         */
        public Builder setProcessedVertices(long value) {
          bitField0_ |= 0x00000020;
          processedVertices_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional sint64 processedVertices = 6;</code>
         */
        public Builder clearProcessedVertices() {
          bitField0_ = (bitField0_ & ~0x00000020);
          processedVertices_ = 0L;
          onChanged();
          return this;
        }

        // optional sint64 nOfPartitions = 7;
        private long nOfPartitions_ ;
        /**
         * <code>optional sint64 nOfPartitions = 7;</code>
         */
        public boolean hasNOfPartitions() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional sint64 nOfPartitions = 7;</code>
         */
        public long getNOfPartitions() {
          return nOfPartitions_;
        }
        /**
         * <code>optional sint64 nOfPartitions = 7;</code>
         */
        public Builder setNOfPartitions(long value) {
          bitField0_ |= 0x00000040;
          nOfPartitions_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional sint64 nOfPartitions = 7;</code>
         */
        public Builder clearNOfPartitions() {
          bitField0_ = (bitField0_ & ~0x00000040);
          nOfPartitions_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo)
      }

      static {
        defaultInstance = new SuperstepInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo)
    }

    private int bitField0_;
    // required int32 worker = 1;
    public static final int WORKER_FIELD_NUMBER = 1;
    private int worker_;
    /**
     * <code>required int32 worker = 1;</code>
     */
    public boolean hasWorker() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 worker = 1;</code>
     */
    public int getWorker() {
      return worker_;
    }

    // repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;
    public static final int SUPERSTEPINFO_FIELD_NUMBER = 2;
    private java.util.List<com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo> superstepInfo_;
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    public java.util.List<com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo> getSuperstepInfoList() {
      return superstepInfo_;
    }
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    public java.util.List<? extends com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder> 
        getSuperstepInfoOrBuilderList() {
      return superstepInfo_;
    }
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    public int getSuperstepInfoCount() {
      return superstepInfo_.size();
    }
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo getSuperstepInfo(int index) {
      return superstepInfo_.get(index);
    }
    /**
     * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
     */
    public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder getSuperstepInfoOrBuilder(
        int index) {
      return superstepInfo_.get(index);
    }

    private void initFields() {
      worker_ = 0;
      superstepInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWorker()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSuperstepInfoCount(); i++) {
        if (!getSuperstepInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, worker_);
      }
      for (int i = 0; i < superstepInfo_.size(); i++) {
        output.writeMessage(2, superstepInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, worker_);
      }
      for (int i = 0; i < superstepInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, superstepInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protobuf.ExecSuperstepWorkerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.class, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.Builder.class);
      }

      // Construct using com.unipg.profiler.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSuperstepInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        worker_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (superstepInfoBuilder_ == null) {
          superstepInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          superstepInfoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.internal_static_Protobuf_ExecSuperstepWorkerInfo_descriptor;
      }

      public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo getDefaultInstanceForType() {
        return com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.getDefaultInstance();
      }

      public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo build() {
        com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo buildPartial() {
        com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo result = new com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.worker_ = worker_;
        if (superstepInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            superstepInfo_ = java.util.Collections.unmodifiableList(superstepInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.superstepInfo_ = superstepInfo_;
        } else {
          result.superstepInfo_ = superstepInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo) {
          return mergeFrom((com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo other) {
        if (other == com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.getDefaultInstance()) return this;
        if (other.hasWorker()) {
          setWorker(other.getWorker());
        }
        if (superstepInfoBuilder_ == null) {
          if (!other.superstepInfo_.isEmpty()) {
            if (superstepInfo_.isEmpty()) {
              superstepInfo_ = other.superstepInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSuperstepInfoIsMutable();
              superstepInfo_.addAll(other.superstepInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.superstepInfo_.isEmpty()) {
            if (superstepInfoBuilder_.isEmpty()) {
              superstepInfoBuilder_.dispose();
              superstepInfoBuilder_ = null;
              superstepInfo_ = other.superstepInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              superstepInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSuperstepInfoFieldBuilder() : null;
            } else {
              superstepInfoBuilder_.addAllMessages(other.superstepInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWorker()) {
          
          return false;
        }
        for (int i = 0; i < getSuperstepInfoCount(); i++) {
          if (!getSuperstepInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 worker = 1;
      private int worker_ ;
      /**
       * <code>required int32 worker = 1;</code>
       */
      public boolean hasWorker() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 worker = 1;</code>
       */
      public int getWorker() {
        return worker_;
      }
      /**
       * <code>required int32 worker = 1;</code>
       */
      public Builder setWorker(int value) {
        bitField0_ |= 0x00000001;
        worker_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 worker = 1;</code>
       */
      public Builder clearWorker() {
        bitField0_ = (bitField0_ & ~0x00000001);
        worker_ = 0;
        onChanged();
        return this;
      }

      // repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;
      private java.util.List<com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo> superstepInfo_ =
        java.util.Collections.emptyList();
      private void ensureSuperstepInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          superstepInfo_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo>(superstepInfo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder> superstepInfoBuilder_;

      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo> getSuperstepInfoList() {
        if (superstepInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(superstepInfo_);
        } else {
          return superstepInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public int getSuperstepInfoCount() {
        if (superstepInfoBuilder_ == null) {
          return superstepInfo_.size();
        } else {
          return superstepInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo getSuperstepInfo(int index) {
        if (superstepInfoBuilder_ == null) {
          return superstepInfo_.get(index);
        } else {
          return superstepInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public Builder setSuperstepInfo(
          int index, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo value) {
        if (superstepInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuperstepInfoIsMutable();
          superstepInfo_.set(index, value);
          onChanged();
        } else {
          superstepInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public Builder setSuperstepInfo(
          int index, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder builderForValue) {
        if (superstepInfoBuilder_ == null) {
          ensureSuperstepInfoIsMutable();
          superstepInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          superstepInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public Builder addSuperstepInfo(com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo value) {
        if (superstepInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuperstepInfoIsMutable();
          superstepInfo_.add(value);
          onChanged();
        } else {
          superstepInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public Builder addSuperstepInfo(
          int index, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo value) {
        if (superstepInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuperstepInfoIsMutable();
          superstepInfo_.add(index, value);
          onChanged();
        } else {
          superstepInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public Builder addSuperstepInfo(
          com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder builderForValue) {
        if (superstepInfoBuilder_ == null) {
          ensureSuperstepInfoIsMutable();
          superstepInfo_.add(builderForValue.build());
          onChanged();
        } else {
          superstepInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public Builder addSuperstepInfo(
          int index, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder builderForValue) {
        if (superstepInfoBuilder_ == null) {
          ensureSuperstepInfoIsMutable();
          superstepInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          superstepInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public Builder addAllSuperstepInfo(
          java.lang.Iterable<? extends com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo> values) {
        if (superstepInfoBuilder_ == null) {
          ensureSuperstepInfoIsMutable();
          super.addAll(values, superstepInfo_);
          onChanged();
        } else {
          superstepInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public Builder clearSuperstepInfo() {
        if (superstepInfoBuilder_ == null) {
          superstepInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          superstepInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public Builder removeSuperstepInfo(int index) {
        if (superstepInfoBuilder_ == null) {
          ensureSuperstepInfoIsMutable();
          superstepInfo_.remove(index);
          onChanged();
        } else {
          superstepInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder getSuperstepInfoBuilder(
          int index) {
        return getSuperstepInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder getSuperstepInfoOrBuilder(
          int index) {
        if (superstepInfoBuilder_ == null) {
          return superstepInfo_.get(index);  } else {
          return superstepInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public java.util.List<? extends com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder> 
           getSuperstepInfoOrBuilderList() {
        if (superstepInfoBuilder_ != null) {
          return superstepInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(superstepInfo_);
        }
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder addSuperstepInfoBuilder() {
        return getSuperstepInfoFieldBuilder().addBuilder(
            com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder addSuperstepInfoBuilder(
          int index) {
        return getSuperstepInfoFieldBuilder().addBuilder(
            index, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.ExecSuperstepWorkerInfo.SuperstepInfo superstepInfo = 2;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder> 
           getSuperstepInfoBuilderList() {
        return getSuperstepInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder> 
          getSuperstepInfoFieldBuilder() {
        if (superstepInfoBuilder_ == null) {
          superstepInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfo.Builder, com.unipg.givip.common.protoutils.ExecutedSuperstepWorkerInfoProto.ExecSuperstepWorkerInfo.SuperstepInfoOrBuilder>(
                  superstepInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          superstepInfo_ = null;
        }
        return superstepInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Protobuf.ExecSuperstepWorkerInfo)
    }

    static {
      defaultInstance = new ExecSuperstepWorkerInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Protobuf.ExecSuperstepWorkerInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_ExecSuperstepWorkerInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protobuf_ExecSuperstepWorkerInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!executedsuperstepworkerinfo.proto\022\010Pro" +
      "tobuf\"\273\002\n\027ExecSuperstepWorkerInfo\022\016\n\006wor" +
      "ker\030\001 \002(\005\022F\n\rsuperstepInfo\030\002 \003(\0132/.Proto" +
      "buf.ExecSuperstepWorkerInfo.SuperstepInf" +
      "o\032\307\001\n\rSuperstepInfo\022 \n\017computationName\030\001" +
      " \001(\t:\007UNKNOWN\022\026\n\016superstepIndex\030\002 \002(\022\022\027\n" +
      "\017computationSecs\030\003 \002(\001\022\026\n\016gcLengthMillis" +
      "\030\004 \001(\001\022\031\n\021waitingTimeMillis\030\005 \001(\001\022\031\n\021pro" +
      "cessedVertices\030\006 \001(\022\022\025\n\rnOfPartitions\030\007 " +
      "\001(\022B/\n\013com.unipg.profiler.common.protoutilsB ExecutedSuperstepWor",
      "kerInfoProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Protobuf_ExecSuperstepWorkerInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Protobuf_ExecSuperstepWorkerInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protobuf_ExecSuperstepWorkerInfo_descriptor,
              new java.lang.String[] { "Worker", "SuperstepInfo", });
          internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_descriptor =
            internal_static_Protobuf_ExecSuperstepWorkerInfo_descriptor.getNestedTypes().get(0);
          internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protobuf_ExecSuperstepWorkerInfo_SuperstepInfo_descriptor,
              new java.lang.String[] { "ComputationName", "SuperstepIndex", "ComputationSecs", "GcLengthMillis", "WaitingTimeMillis", "ProcessedVertices", "NOfPartitions", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
