// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hierarchy.proto

package com.unipg.givip.common.protoutils;

import edu.umd.cs.findbugs.annotations.SuppressWarnings;

public final class HierarchyProtoBook {
  private HierarchyProtoBook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SingleWorkerTreeHierarchyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 worker = 1;
    /**
     * <code>required int32 worker = 1;</code>
     */
    boolean hasWorker();
    /**
     * <code>required int32 worker = 1;</code>
     */
    int getWorker();

    // required string rack = 2;
    /**
     * <code>required string rack = 2;</code>
     */
    boolean hasRack();
    /**
     * <code>required string rack = 2;</code>
     */
    java.lang.String getRack();
    /**
     * <code>required string rack = 2;</code>
     */
    com.google.protobuf.ByteString
        getRackBytes();

    // required string hostName = 3;
    /**
     * <code>required string hostName = 3;</code>
     */
    boolean hasHostName();
    /**
     * <code>required string hostName = 3;</code>
     */
    java.lang.String getHostName();
    /**
     * <code>required string hostName = 3;</code>
     */
    com.google.protobuf.ByteString
        getHostNameBytes();
  }
  /**
   * Protobuf type {@code Protobuf.SingleWorkerTreeHierarchy}
   */
  public static final class SingleWorkerTreeHierarchy extends
      com.google.protobuf.GeneratedMessage
      implements SingleWorkerTreeHierarchyOrBuilder {
    @SuppressWarnings(justification="No bug", value="SE_BAD_FIELD")
    // Use SingleWorkerTreeHierarchy.newBuilder() to construct.
    private SingleWorkerTreeHierarchy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SingleWorkerTreeHierarchy(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SingleWorkerTreeHierarchy defaultInstance;
    public static SingleWorkerTreeHierarchy getDefaultInstance() {
      return defaultInstance;
    }

    public SingleWorkerTreeHierarchy getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SingleWorkerTreeHierarchy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              worker_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rack_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              hostName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_SingleWorkerTreeHierarchy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_SingleWorkerTreeHierarchy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.class, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder.class);
    }

    public static final com.google.protobuf.Parser<SingleWorkerTreeHierarchy> PARSER =
        new com.google.protobuf.AbstractParser<SingleWorkerTreeHierarchy>() {
      public SingleWorkerTreeHierarchy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SingleWorkerTreeHierarchy(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SingleWorkerTreeHierarchy> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 worker = 1;
    public static final int WORKER_FIELD_NUMBER = 1;
    private int worker_;
    /**
     * <code>required int32 worker = 1;</code>
     */
    public boolean hasWorker() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 worker = 1;</code>
     */
    public int getWorker() {
      return worker_;
    }

    // required string rack = 2;
    public static final int RACK_FIELD_NUMBER = 2;
    private java.lang.Object rack_;
    /**
     * <code>required string rack = 2;</code>
     */
    public boolean hasRack() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string rack = 2;</code>
     */
    public java.lang.String getRack() {
      java.lang.Object ref = rack_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rack_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rack = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRackBytes() {
      java.lang.Object ref = rack_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rack_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string hostName = 3;
    public static final int HOSTNAME_FIELD_NUMBER = 3;
    private java.lang.Object hostName_;
    /**
     * <code>required string hostName = 3;</code>
     */
    public boolean hasHostName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string hostName = 3;</code>
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hostName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hostName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      worker_ = 0;
      rack_ = "";
      hostName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWorker()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRack()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHostName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, worker_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRackBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHostNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, worker_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRackBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHostNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protobuf.SingleWorkerTreeHierarchy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_SingleWorkerTreeHierarchy_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_SingleWorkerTreeHierarchy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.class, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder.class);
      }

      // Construct using org.apache.giraph.master.HierarchyProtoBook.SingleWorkerTreeHierarchy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
//        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        worker_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rack_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        hostName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_SingleWorkerTreeHierarchy_descriptor;
      }

      public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy getDefaultInstanceForType() {
        return com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.getDefaultInstance();
      }

      public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy build() {
        com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy buildPartial() {
        com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy result = new com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.worker_ = worker_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rack_ = rack_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hostName_ = hostName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy) {
          return mergeFrom((com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy other) {
        if (other == com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.getDefaultInstance()) return this;
        if (other.hasWorker()) {
          setWorker(other.getWorker());
        }
        if (other.hasRack()) {
          bitField0_ |= 0x00000002;
          rack_ = other.rack_;
          onChanged();
        }
        if (other.hasHostName()) {
          bitField0_ |= 0x00000004;
          hostName_ = other.hostName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWorker()) {
          
          return false;
        }
        if (!hasRack()) {
          
          return false;
        }
        if (!hasHostName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 worker = 1;
      private int worker_ ;
      /**
       * <code>required int32 worker = 1;</code>
       */
      public boolean hasWorker() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 worker = 1;</code>
       */
      public int getWorker() {
        return worker_;
      }
      /**
       * <code>required int32 worker = 1;</code>
       */
      public Builder setWorker(int value) {
        bitField0_ |= 0x00000001;
        worker_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 worker = 1;</code>
       */
      public Builder clearWorker() {
        bitField0_ = (bitField0_ & ~0x00000001);
        worker_ = 0;
        onChanged();
        return this;
      }

      // required string rack = 2;
      private java.lang.Object rack_ = "";
      /**
       * <code>required string rack = 2;</code>
       */
      public boolean hasRack() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string rack = 2;</code>
       */
      public java.lang.String getRack() {
        java.lang.Object ref = rack_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rack_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string rack = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRackBytes() {
        java.lang.Object ref = rack_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rack_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rack = 2;</code>
       */
      public Builder setRack(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rack = 2;</code>
       */
      public Builder clearRack() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rack_ = getDefaultInstance().getRack();
        onChanged();
        return this;
      }
      /**
       * <code>required string rack = 2;</code>
       */
      public Builder setRackBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rack_ = value;
        onChanged();
        return this;
      }

      // required string hostName = 3;
      private java.lang.Object hostName_ = "";
      /**
       * <code>required string hostName = 3;</code>
       */
      public boolean hasHostName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string hostName = 3;</code>
       */
      public java.lang.String getHostName() {
        java.lang.Object ref = hostName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hostName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hostName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        java.lang.Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hostName = 3;</code>
       */
      public Builder setHostName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hostName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hostName = 3;</code>
       */
      public Builder clearHostName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hostName_ = getDefaultInstance().getHostName();
        onChanged();
        return this;
      }
      /**
       * <code>required string hostName = 3;</code>
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hostName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Protobuf.SingleWorkerTreeHierarchy)
    }

    static {
      defaultInstance = new SingleWorkerTreeHierarchy(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Protobuf.SingleWorkerTreeHierarchy)
  }

  public interface WorkerHierarchyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    java.util.List<com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy> 
        getSingleWorkerTreeHierarchyList();
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy getSingleWorkerTreeHierarchy(int index);
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    int getSingleWorkerTreeHierarchyCount();
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    java.util.List<? extends com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder> 
        getSingleWorkerTreeHierarchyOrBuilderList();
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder getSingleWorkerTreeHierarchyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Protobuf.WorkerHierarchy}
   */
  public static final class WorkerHierarchy extends
      com.google.protobuf.GeneratedMessage
      implements WorkerHierarchyOrBuilder {
    @SuppressWarnings(justification="No bug", value="SE_BAD_FIELD")
    // Use WorkerHierarchy.newBuilder() to construct.
    private WorkerHierarchy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorkerHierarchy(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorkerHierarchy defaultInstance;
    public static WorkerHierarchy getDefaultInstance() {
      return defaultInstance;
    }

    public WorkerHierarchy getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorkerHierarchy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                singleWorkerTreeHierarchy_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy>();
                mutable_bitField0_ |= 0x00000001;
              }
              singleWorkerTreeHierarchy_.add(input.readMessage(com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          singleWorkerTreeHierarchy_ = java.util.Collections.unmodifiableList(singleWorkerTreeHierarchy_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_WorkerHierarchy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_WorkerHierarchy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy.class, com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy.Builder.class);
    }

    public static final com.google.protobuf.Parser<WorkerHierarchy> PARSER =
        new com.google.protobuf.AbstractParser<WorkerHierarchy>() {
      public WorkerHierarchy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorkerHierarchy(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorkerHierarchy> getParserForType() {
      return PARSER;
    }

    // repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;
    public static final int SINGLEWORKERTREEHIERARCHY_FIELD_NUMBER = 1;
    private java.util.List<com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy> singleWorkerTreeHierarchy_;
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    public java.util.List<com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy> getSingleWorkerTreeHierarchyList() {
      return singleWorkerTreeHierarchy_;
    }
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    public java.util.List<? extends com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder> 
        getSingleWorkerTreeHierarchyOrBuilderList() {
      return singleWorkerTreeHierarchy_;
    }
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    public int getSingleWorkerTreeHierarchyCount() {
      return singleWorkerTreeHierarchy_.size();
    }
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy getSingleWorkerTreeHierarchy(int index) {
      return singleWorkerTreeHierarchy_.get(index);
    }
    /**
     * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
     */
    public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder getSingleWorkerTreeHierarchyOrBuilder(
        int index) {
      return singleWorkerTreeHierarchy_.get(index);
    }

    private void initFields() {
      singleWorkerTreeHierarchy_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getSingleWorkerTreeHierarchyCount(); i++) {
        if (!getSingleWorkerTreeHierarchy(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < singleWorkerTreeHierarchy_.size(); i++) {
        output.writeMessage(1, singleWorkerTreeHierarchy_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < singleWorkerTreeHierarchy_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, singleWorkerTreeHierarchy_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protobuf.WorkerHierarchy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_WorkerHierarchy_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_WorkerHierarchy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy.class, com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy.Builder.class);
      }

      // Construct using org.apache.giraph.master.HierarchyProtoBook.WorkerHierarchy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSingleWorkerTreeHierarchyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          singleWorkerTreeHierarchy_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          singleWorkerTreeHierarchyBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unipg.givip.common.protoutils.HierarchyProtoBook.internal_static_Protobuf_WorkerHierarchy_descriptor;
      }

      public com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy getDefaultInstanceForType() {
        return com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy.getDefaultInstance();
      }

      public com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy build() {
        com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy buildPartial() {
        com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy result = new com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy(this);
        int from_bitField0_ = bitField0_;
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            singleWorkerTreeHierarchy_ = java.util.Collections.unmodifiableList(singleWorkerTreeHierarchy_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.singleWorkerTreeHierarchy_ = singleWorkerTreeHierarchy_;
        } else {
          result.singleWorkerTreeHierarchy_ = singleWorkerTreeHierarchyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy) {
          return mergeFrom((com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy other) {
        if (other == com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy.getDefaultInstance()) return this;
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          if (!other.singleWorkerTreeHierarchy_.isEmpty()) {
            if (singleWorkerTreeHierarchy_.isEmpty()) {
              singleWorkerTreeHierarchy_ = other.singleWorkerTreeHierarchy_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSingleWorkerTreeHierarchyIsMutable();
              singleWorkerTreeHierarchy_.addAll(other.singleWorkerTreeHierarchy_);
            }
            onChanged();
          }
        } else {
          if (!other.singleWorkerTreeHierarchy_.isEmpty()) {
            if (singleWorkerTreeHierarchyBuilder_.isEmpty()) {
              singleWorkerTreeHierarchyBuilder_.dispose();
              singleWorkerTreeHierarchyBuilder_ = null;
              singleWorkerTreeHierarchy_ = other.singleWorkerTreeHierarchy_;
              bitField0_ = (bitField0_ & ~0x00000001);
              singleWorkerTreeHierarchyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSingleWorkerTreeHierarchyFieldBuilder() : null;
            } else {
              singleWorkerTreeHierarchyBuilder_.addAllMessages(other.singleWorkerTreeHierarchy_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSingleWorkerTreeHierarchyCount(); i++) {
          if (!getSingleWorkerTreeHierarchy(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unipg.givip.common.protoutils.HierarchyProtoBook.WorkerHierarchy) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;
      private java.util.List<com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy> singleWorkerTreeHierarchy_ =
        java.util.Collections.emptyList();
      private void ensureSingleWorkerTreeHierarchyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          singleWorkerTreeHierarchy_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy>(singleWorkerTreeHierarchy_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder> singleWorkerTreeHierarchyBuilder_;

      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy> getSingleWorkerTreeHierarchyList() {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(singleWorkerTreeHierarchy_);
        } else {
          return singleWorkerTreeHierarchyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public int getSingleWorkerTreeHierarchyCount() {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          return singleWorkerTreeHierarchy_.size();
        } else {
          return singleWorkerTreeHierarchyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy getSingleWorkerTreeHierarchy(int index) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          return singleWorkerTreeHierarchy_.get(index);
        } else {
          return singleWorkerTreeHierarchyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public Builder setSingleWorkerTreeHierarchy(
          int index, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy value) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSingleWorkerTreeHierarchyIsMutable();
          singleWorkerTreeHierarchy_.set(index, value);
          onChanged();
        } else {
          singleWorkerTreeHierarchyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public Builder setSingleWorkerTreeHierarchy(
          int index, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder builderForValue) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          ensureSingleWorkerTreeHierarchyIsMutable();
          singleWorkerTreeHierarchy_.set(index, builderForValue.build());
          onChanged();
        } else {
          singleWorkerTreeHierarchyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public Builder addSingleWorkerTreeHierarchy(com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy value) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSingleWorkerTreeHierarchyIsMutable();
          singleWorkerTreeHierarchy_.add(value);
          onChanged();
        } else {
          singleWorkerTreeHierarchyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public Builder addSingleWorkerTreeHierarchy(
          int index, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy value) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSingleWorkerTreeHierarchyIsMutable();
          singleWorkerTreeHierarchy_.add(index, value);
          onChanged();
        } else {
          singleWorkerTreeHierarchyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public Builder addSingleWorkerTreeHierarchy(
          com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder builderForValue) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          ensureSingleWorkerTreeHierarchyIsMutable();
          singleWorkerTreeHierarchy_.add(builderForValue.build());
          onChanged();
        } else {
          singleWorkerTreeHierarchyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public Builder addSingleWorkerTreeHierarchy(
          int index, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder builderForValue) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          ensureSingleWorkerTreeHierarchyIsMutable();
          singleWorkerTreeHierarchy_.add(index, builderForValue.build());
          onChanged();
        } else {
          singleWorkerTreeHierarchyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public Builder addAllSingleWorkerTreeHierarchy(
          java.lang.Iterable<? extends com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy> values) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          ensureSingleWorkerTreeHierarchyIsMutable();
          super.addAll(values, singleWorkerTreeHierarchy_);
          onChanged();
        } else {
          singleWorkerTreeHierarchyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public Builder clearSingleWorkerTreeHierarchy() {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          singleWorkerTreeHierarchy_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          singleWorkerTreeHierarchyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public Builder removeSingleWorkerTreeHierarchy(int index) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          ensureSingleWorkerTreeHierarchyIsMutable();
          singleWorkerTreeHierarchy_.remove(index);
          onChanged();
        } else {
          singleWorkerTreeHierarchyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder getSingleWorkerTreeHierarchyBuilder(
          int index) {
        return getSingleWorkerTreeHierarchyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder getSingleWorkerTreeHierarchyOrBuilder(
          int index) {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          return singleWorkerTreeHierarchy_.get(index);  } else {
          return singleWorkerTreeHierarchyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public java.util.List<? extends com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder> 
           getSingleWorkerTreeHierarchyOrBuilderList() {
        if (singleWorkerTreeHierarchyBuilder_ != null) {
          return singleWorkerTreeHierarchyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(singleWorkerTreeHierarchy_);
        }
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder addSingleWorkerTreeHierarchyBuilder() {
        return getSingleWorkerTreeHierarchyFieldBuilder().addBuilder(
            com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder addSingleWorkerTreeHierarchyBuilder(
          int index) {
        return getSingleWorkerTreeHierarchyFieldBuilder().addBuilder(
            index, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.SingleWorkerTreeHierarchy singleWorkerTreeHierarchy = 1;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder> 
           getSingleWorkerTreeHierarchyBuilderList() {
        return getSingleWorkerTreeHierarchyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder> 
          getSingleWorkerTreeHierarchyFieldBuilder() {
        if (singleWorkerTreeHierarchyBuilder_ == null) {
          singleWorkerTreeHierarchyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchy.Builder, com.unipg.givip.common.protoutils.HierarchyProtoBook.SingleWorkerTreeHierarchyOrBuilder>(
                  singleWorkerTreeHierarchy_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          singleWorkerTreeHierarchy_ = null;
        }
        return singleWorkerTreeHierarchyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Protobuf.WorkerHierarchy)
    }

    static {
      defaultInstance = new WorkerHierarchy(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Protobuf.WorkerHierarchy)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_SingleWorkerTreeHierarchy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protobuf_SingleWorkerTreeHierarchy_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_WorkerHierarchy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protobuf_WorkerHierarchy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017hierarchy.proto\022\010Protobuf\"K\n\031SingleWor" +
      "kerTreeHierarchy\022\016\n\006worker\030\001 \002(\005\022\014\n\004rack" +
      "\030\002 \002(\t\022\020\n\010hostName\030\003 \002(\t\"Y\n\017WorkerHierar" +
      "chy\022F\n\031singleWorkerTreeHierarchy\030\001 \003(\0132#" +
      ".Protobuf.SingleWorkerTreeHierarchyB!\n\013c" +
      "om.messageB\022HierarchyProtoBook"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Protobuf_SingleWorkerTreeHierarchy_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Protobuf_SingleWorkerTreeHierarchy_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protobuf_SingleWorkerTreeHierarchy_descriptor,
              new java.lang.String[] { "Worker", "Rack", "HostName", });
          internal_static_Protobuf_WorkerHierarchy_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Protobuf_WorkerHierarchy_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protobuf_WorkerHierarchy_descriptor,
              new java.lang.String[] { "SingleWorkerTreeHierarchy", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
