// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: latenciesbook.proto

package com.unipg.givip.common.protoutils;

public final class LatenciesProtoBook {
  private LatenciesProtoBook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordedLatencyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protobuf.RecordedLatency)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ping_source = 1;</code>
     */
    boolean hasPingSource();
    /**
     * <code>required string ping_source = 1;</code>
     */
    java.lang.String getPingSource();
    /**
     * <code>required string ping_source = 1;</code>
     */
    com.google.protobuf.ByteString
        getPingSourceBytes();

    /**
     * <code>required string ping_target = 2;</code>
     */
    boolean hasPingTarget();
    /**
     * <code>required string ping_target = 2;</code>
     */
    java.lang.String getPingTarget();
    /**
     * <code>required string ping_target = 2;</code>
     */
    com.google.protobuf.ByteString
        getPingTargetBytes();

    /**
     * <code>required int64 latency_ms = 3;</code>
     */
    boolean hasLatencyMs();
    /**
     * <code>required int64 latency_ms = 3;</code>
     */
    long getLatencyMs();
  }
  /**
   * Protobuf type {@code Protobuf.RecordedLatency}
   */
  public  static final class RecordedLatency extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protobuf.RecordedLatency)
      RecordedLatencyOrBuilder {
    // Use RecordedLatency.newBuilder() to construct.
    private RecordedLatency(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecordedLatency() {
      pingSource_ = "";
      pingTarget_ = "";
      latencyMs_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecordedLatency(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              pingSource_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              pingTarget_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              latencyMs_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_RecordedLatency_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_RecordedLatency_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.class, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder.class);
    }

    private int bitField0_;
    public static final int PING_SOURCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object pingSource_;
    /**
     * <code>required string ping_source = 1;</code>
     */
    public boolean hasPingSource() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ping_source = 1;</code>
     */
    public java.lang.String getPingSource() {
      java.lang.Object ref = pingSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pingSource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ping_source = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPingSourceBytes() {
      java.lang.Object ref = pingSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pingSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PING_TARGET_FIELD_NUMBER = 2;
    private volatile java.lang.Object pingTarget_;
    /**
     * <code>required string ping_target = 2;</code>
     */
    public boolean hasPingTarget() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ping_target = 2;</code>
     */
    public java.lang.String getPingTarget() {
      java.lang.Object ref = pingTarget_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pingTarget_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ping_target = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPingTargetBytes() {
      java.lang.Object ref = pingTarget_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pingTarget_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATENCY_MS_FIELD_NUMBER = 3;
    private long latencyMs_;
    /**
     * <code>required int64 latency_ms = 3;</code>
     */
    public boolean hasLatencyMs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 latency_ms = 3;</code>
     */
    public long getLatencyMs() {
      return latencyMs_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPingSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPingTarget()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatencyMs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pingSource_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pingTarget_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, latencyMs_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pingSource_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pingTarget_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, latencyMs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency)) {
        return super.equals(obj);
      }
      com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency other = (com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency) obj;

      boolean result = true;
      result = result && (hasPingSource() == other.hasPingSource());
      if (hasPingSource()) {
        result = result && getPingSource()
            .equals(other.getPingSource());
      }
      result = result && (hasPingTarget() == other.hasPingTarget());
      if (hasPingTarget()) {
        result = result && getPingTarget()
            .equals(other.getPingTarget());
      }
      result = result && (hasLatencyMs() == other.hasLatencyMs());
      if (hasLatencyMs()) {
        result = result && (getLatencyMs()
            == other.getLatencyMs());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPingSource()) {
        hash = (37 * hash) + PING_SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getPingSource().hashCode();
      }
      if (hasPingTarget()) {
        hash = (37 * hash) + PING_TARGET_FIELD_NUMBER;
        hash = (53 * hash) + getPingTarget().hashCode();
      }
      if (hasLatencyMs()) {
        hash = (37 * hash) + LATENCY_MS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLatencyMs());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protobuf.RecordedLatency}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protobuf.RecordedLatency)
        com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_RecordedLatency_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_RecordedLatency_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.class, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder.class);
      }

      // Construct using com.unipg.profiler.common.protoutils.LatenciesProtoBook.RecordedLatency.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pingSource_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pingTarget_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        latencyMs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_RecordedLatency_descriptor;
      }

      public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency getDefaultInstanceForType() {
        return com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.getDefaultInstance();
      }

      public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency build() {
        com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency buildPartial() {
        com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency result = new com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pingSource_ = pingSource_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pingTarget_ = pingTarget_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.latencyMs_ = latencyMs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency) {
          return mergeFrom((com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency other) {
        if (other == com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.getDefaultInstance()) return this;
        if (other.hasPingSource()) {
          bitField0_ |= 0x00000001;
          pingSource_ = other.pingSource_;
          onChanged();
        }
        if (other.hasPingTarget()) {
          bitField0_ |= 0x00000002;
          pingTarget_ = other.pingTarget_;
          onChanged();
        }
        if (other.hasLatencyMs()) {
          setLatencyMs(other.getLatencyMs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPingSource()) {
          return false;
        }
        if (!hasPingTarget()) {
          return false;
        }
        if (!hasLatencyMs()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object pingSource_ = "";
      /**
       * <code>required string ping_source = 1;</code>
       */
      public boolean hasPingSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ping_source = 1;</code>
       */
      public java.lang.String getPingSource() {
        java.lang.Object ref = pingSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pingSource_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ping_source = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPingSourceBytes() {
        java.lang.Object ref = pingSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pingSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ping_source = 1;</code>
       */
      public Builder setPingSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pingSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ping_source = 1;</code>
       */
      public Builder clearPingSource() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pingSource_ = getDefaultInstance().getPingSource();
        onChanged();
        return this;
      }
      /**
       * <code>required string ping_source = 1;</code>
       */
      public Builder setPingSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pingSource_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pingTarget_ = "";
      /**
       * <code>required string ping_target = 2;</code>
       */
      public boolean hasPingTarget() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ping_target = 2;</code>
       */
      public java.lang.String getPingTarget() {
        java.lang.Object ref = pingTarget_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pingTarget_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ping_target = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPingTargetBytes() {
        java.lang.Object ref = pingTarget_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pingTarget_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ping_target = 2;</code>
       */
      public Builder setPingTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pingTarget_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ping_target = 2;</code>
       */
      public Builder clearPingTarget() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pingTarget_ = getDefaultInstance().getPingTarget();
        onChanged();
        return this;
      }
      /**
       * <code>required string ping_target = 2;</code>
       */
      public Builder setPingTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pingTarget_ = value;
        onChanged();
        return this;
      }

      private long latencyMs_ ;
      /**
       * <code>required int64 latency_ms = 3;</code>
       */
      public boolean hasLatencyMs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 latency_ms = 3;</code>
       */
      public long getLatencyMs() {
        return latencyMs_;
      }
      /**
       * <code>required int64 latency_ms = 3;</code>
       */
      public Builder setLatencyMs(long value) {
        bitField0_ |= 0x00000004;
        latencyMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 latency_ms = 3;</code>
       */
      public Builder clearLatencyMs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latencyMs_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protobuf.RecordedLatency)
    }

    // @@protoc_insertion_point(class_scope:Protobuf.RecordedLatency)
    private static final com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency();
    }

    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RecordedLatency>
        PARSER = new com.google.protobuf.AbstractParser<RecordedLatency>() {
      public RecordedLatency parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RecordedLatency(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecordedLatency> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecordedLatency> getParserForType() {
      return PARSER;
    }

    public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LatenciesBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protobuf.LatenciesBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    java.util.List<com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency> 
        getRecordedLatencyList();
    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency getRecordedLatency(int index);
    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    int getRecordedLatencyCount();
    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    java.util.List<? extends com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder> 
        getRecordedLatencyOrBuilderList();
    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder getRecordedLatencyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Protobuf.LatenciesBook}
   */
  public  static final class LatenciesBook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protobuf.LatenciesBook)
      LatenciesBookOrBuilder {
    // Use LatenciesBook.newBuilder() to construct.
    private LatenciesBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LatenciesBook() {
      recordedLatency_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LatenciesBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                recordedLatency_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency>();
                mutable_bitField0_ |= 0x00000001;
              }
              recordedLatency_.add(
                  input.readMessage(com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          recordedLatency_ = java.util.Collections.unmodifiableList(recordedLatency_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_LatenciesBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_LatenciesBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook.class, com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook.Builder.class);
    }

    public static final int RECORDED_LATENCY_FIELD_NUMBER = 1;
    private java.util.List<com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency> recordedLatency_;
    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    public java.util.List<com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency> getRecordedLatencyList() {
      return recordedLatency_;
    }
    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    public java.util.List<? extends com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder> 
        getRecordedLatencyOrBuilderList() {
      return recordedLatency_;
    }
    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    public int getRecordedLatencyCount() {
      return recordedLatency_.size();
    }
    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency getRecordedLatency(int index) {
      return recordedLatency_.get(index);
    }
    /**
     * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
     */
    public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder getRecordedLatencyOrBuilder(
        int index) {
      return recordedLatency_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getRecordedLatencyCount(); i++) {
        if (!getRecordedLatency(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < recordedLatency_.size(); i++) {
        output.writeMessage(1, recordedLatency_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < recordedLatency_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, recordedLatency_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook)) {
        return super.equals(obj);
      }
      com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook other = (com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook) obj;

      boolean result = true;
      result = result && getRecordedLatencyList()
          .equals(other.getRecordedLatencyList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getRecordedLatencyCount() > 0) {
        hash = (37 * hash) + RECORDED_LATENCY_FIELD_NUMBER;
        hash = (53 * hash) + getRecordedLatencyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protobuf.LatenciesBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protobuf.LatenciesBook)
        com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_LatenciesBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_LatenciesBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook.class, com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook.Builder.class);
      }

      // Construct using com.unipg.profiler.common.protoutils.LatenciesProtoBook.LatenciesBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecordedLatencyFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (recordedLatencyBuilder_ == null) {
          recordedLatency_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          recordedLatencyBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unipg.givip.common.protoutils.LatenciesProtoBook.internal_static_Protobuf_LatenciesBook_descriptor;
      }

      public com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook getDefaultInstanceForType() {
        return com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook.getDefaultInstance();
      }

      public com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook build() {
        com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook buildPartial() {
        com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook result = new com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook(this);
        int from_bitField0_ = bitField0_;
        if (recordedLatencyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            recordedLatency_ = java.util.Collections.unmodifiableList(recordedLatency_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.recordedLatency_ = recordedLatency_;
        } else {
          result.recordedLatency_ = recordedLatencyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook) {
          return mergeFrom((com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook other) {
        if (other == com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook.getDefaultInstance()) return this;
        if (recordedLatencyBuilder_ == null) {
          if (!other.recordedLatency_.isEmpty()) {
            if (recordedLatency_.isEmpty()) {
              recordedLatency_ = other.recordedLatency_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRecordedLatencyIsMutable();
              recordedLatency_.addAll(other.recordedLatency_);
            }
            onChanged();
          }
        } else {
          if (!other.recordedLatency_.isEmpty()) {
            if (recordedLatencyBuilder_.isEmpty()) {
              recordedLatencyBuilder_.dispose();
              recordedLatencyBuilder_ = null;
              recordedLatency_ = other.recordedLatency_;
              bitField0_ = (bitField0_ & ~0x00000001);
              recordedLatencyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecordedLatencyFieldBuilder() : null;
            } else {
              recordedLatencyBuilder_.addAllMessages(other.recordedLatency_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getRecordedLatencyCount(); i++) {
          if (!getRecordedLatency(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency> recordedLatency_ =
        java.util.Collections.emptyList();
      private void ensureRecordedLatencyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          recordedLatency_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency>(recordedLatency_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder> recordedLatencyBuilder_;

      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency> getRecordedLatencyList() {
        if (recordedLatencyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recordedLatency_);
        } else {
          return recordedLatencyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public int getRecordedLatencyCount() {
        if (recordedLatencyBuilder_ == null) {
          return recordedLatency_.size();
        } else {
          return recordedLatencyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency getRecordedLatency(int index) {
        if (recordedLatencyBuilder_ == null) {
          return recordedLatency_.get(index);
        } else {
          return recordedLatencyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public Builder setRecordedLatency(
          int index, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency value) {
        if (recordedLatencyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordedLatencyIsMutable();
          recordedLatency_.set(index, value);
          onChanged();
        } else {
          recordedLatencyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public Builder setRecordedLatency(
          int index, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder builderForValue) {
        if (recordedLatencyBuilder_ == null) {
          ensureRecordedLatencyIsMutable();
          recordedLatency_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordedLatencyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public Builder addRecordedLatency(com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency value) {
        if (recordedLatencyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordedLatencyIsMutable();
          recordedLatency_.add(value);
          onChanged();
        } else {
          recordedLatencyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public Builder addRecordedLatency(
          int index, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency value) {
        if (recordedLatencyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordedLatencyIsMutable();
          recordedLatency_.add(index, value);
          onChanged();
        } else {
          recordedLatencyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public Builder addRecordedLatency(
          com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder builderForValue) {
        if (recordedLatencyBuilder_ == null) {
          ensureRecordedLatencyIsMutable();
          recordedLatency_.add(builderForValue.build());
          onChanged();
        } else {
          recordedLatencyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public Builder addRecordedLatency(
          int index, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder builderForValue) {
        if (recordedLatencyBuilder_ == null) {
          ensureRecordedLatencyIsMutable();
          recordedLatency_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordedLatencyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public Builder addAllRecordedLatency(
          java.lang.Iterable<? extends com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency> values) {
        if (recordedLatencyBuilder_ == null) {
          ensureRecordedLatencyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, recordedLatency_);
          onChanged();
        } else {
          recordedLatencyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public Builder clearRecordedLatency() {
        if (recordedLatencyBuilder_ == null) {
          recordedLatency_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          recordedLatencyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public Builder removeRecordedLatency(int index) {
        if (recordedLatencyBuilder_ == null) {
          ensureRecordedLatencyIsMutable();
          recordedLatency_.remove(index);
          onChanged();
        } else {
          recordedLatencyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder getRecordedLatencyBuilder(
          int index) {
        return getRecordedLatencyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder getRecordedLatencyOrBuilder(
          int index) {
        if (recordedLatencyBuilder_ == null) {
          return recordedLatency_.get(index);  } else {
          return recordedLatencyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public java.util.List<? extends com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder> 
           getRecordedLatencyOrBuilderList() {
        if (recordedLatencyBuilder_ != null) {
          return recordedLatencyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recordedLatency_);
        }
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder addRecordedLatencyBuilder() {
        return getRecordedLatencyFieldBuilder().addBuilder(
            com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder addRecordedLatencyBuilder(
          int index) {
        return getRecordedLatencyFieldBuilder().addBuilder(
            index, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.RecordedLatency recorded_latency = 1;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder> 
           getRecordedLatencyBuilderList() {
        return getRecordedLatencyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder> 
          getRecordedLatencyFieldBuilder() {
        if (recordedLatencyBuilder_ == null) {
          recordedLatencyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatency.Builder, com.unipg.givip.common.protoutils.LatenciesProtoBook.RecordedLatencyOrBuilder>(
                  recordedLatency_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          recordedLatency_ = null;
        }
        return recordedLatencyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protobuf.LatenciesBook)
    }

    // @@protoc_insertion_point(class_scope:Protobuf.LatenciesBook)
    private static final com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook();
    }

    public static com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LatenciesBook>
        PARSER = new com.google.protobuf.AbstractParser<LatenciesBook>() {
      public LatenciesBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LatenciesBook(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LatenciesBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LatenciesBook> getParserForType() {
      return PARSER;
    }

    public com.unipg.givip.common.protoutils.LatenciesProtoBook.LatenciesBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_RecordedLatency_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protobuf_RecordedLatency_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_LatenciesBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protobuf_LatenciesBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023latenciesbook.proto\022\010Protobuf\"O\n\017Recor" +
      "dedLatency\022\023\n\013ping_source\030\001 \002(\t\022\023\n\013ping_" +
      "target\030\002 \002(\t\022\022\n\nlatency_ms\030\003 \002(\003\"D\n\rLate" +
      "nciesBook\0223\n\020recorded_latency\030\001 \003(\0132\031.Pr" +
      "otobuf.RecordedLatencyB9\n#com.unipg.prof" +
      "ilercommon.protoutilsB\022LatenciesProtoBoo" +
      "k"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Protobuf_RecordedLatency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protobuf_RecordedLatency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protobuf_RecordedLatency_descriptor,
        new java.lang.String[] { "PingSource", "PingTarget", "LatencyMs", });
    internal_static_Protobuf_LatenciesBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protobuf_LatenciesBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protobuf_LatenciesBook_descriptor,
        new java.lang.String[] { "RecordedLatency", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
