// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto/messagesbook.proto

package com.unipg.givip.common.protoutils;
import edu.umd.cs.findbugs.annotations.SuppressWarnings;

public final class MessagesProtoBook {
  private MessagesProtoBook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExchangedMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 worker_source_id = 1;
    /**
     * <code>required int32 worker_source_id = 1;</code>
     */
    boolean hasWorkerSourceId();
    /**
     * <code>required int32 worker_source_id = 1;</code>
     */
    int getWorkerSourceId();

    // required int32 worker_dest_id = 2;
    /**
     * <code>required int32 worker_dest_id = 2;</code>
     */
    boolean hasWorkerDestId();
    /**
     * <code>required int32 worker_dest_id = 2;</code>
     */
    int getWorkerDestId();

    // optional int32 messages_number = 3;
    /**
     * <code>optional int32 messages_number = 3;</code>
     */
    boolean hasMessagesNumber();
    /**
     * <code>optional int32 messages_number = 3;</code>
     */
    int getMessagesNumber();

    // optional double messages_byte_size = 4;
    /**
     * <code>optional double messages_byte_size = 4;</code>
     */
    boolean hasMessagesByteSize();
    /**
     * <code>optional double messages_byte_size = 4;</code>
     */
    double getMessagesByteSize();

    // optional bool is_internal_msg = 5 [default = false];
    /**
     * <code>optional bool is_internal_msg = 5 [default = false];</code>
     */
    boolean hasIsInternalMsg();
    /**
     * <code>optional bool is_internal_msg = 5 [default = false];</code>
     */
    boolean getIsInternalMsg();
  }
  /**
   * Protobuf type {@code Protobuf.ExchangedMessage}
   */
  public static final class ExchangedMessage extends
      com.google.protobuf.GeneratedMessage
      implements ExchangedMessageOrBuilder {
    @SuppressWarnings(justification="No bug", value="SE_BAD_FIELD")
    // Use ExchangedMessage.newBuilder() to construct.
    private ExchangedMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExchangedMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExchangedMessage defaultInstance;
    public static ExchangedMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ExchangedMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExchangedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              workerSourceId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              workerDestId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              messagesNumber_ = input.readInt32();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              messagesByteSize_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isInternalMsg_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unipg.givip.common.protoutils.MessagesProtoBook.internal_static_Protobuf_ExchangedMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unipg.givip.common.protoutils.MessagesProtoBook.internal_static_Protobuf_ExchangedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.class, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder.class);
    }

    public static final com.google.protobuf.Parser<ExchangedMessage> PARSER =
        new com.google.protobuf.AbstractParser<ExchangedMessage>() {
      public ExchangedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExchangedMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangedMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 worker_source_id = 1;
    public static final int WORKER_SOURCE_ID_FIELD_NUMBER = 1;
    private int workerSourceId_;
    /**
     * <code>required int32 worker_source_id = 1;</code>
     */
    public boolean hasWorkerSourceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 worker_source_id = 1;</code>
     */
    public int getWorkerSourceId() {
      return workerSourceId_;
    }

    // required int32 worker_dest_id = 2;
    public static final int WORKER_DEST_ID_FIELD_NUMBER = 2;
    private int workerDestId_;
    /**
     * <code>required int32 worker_dest_id = 2;</code>
     */
    public boolean hasWorkerDestId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 worker_dest_id = 2;</code>
     */
    public int getWorkerDestId() {
      return workerDestId_;
    }

    // optional int32 messages_number = 3;
    public static final int MESSAGES_NUMBER_FIELD_NUMBER = 3;
    private int messagesNumber_;
    /**
     * <code>optional int32 messages_number = 3;</code>
     */
    public boolean hasMessagesNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 messages_number = 3;</code>
     */
    public int getMessagesNumber() {
      return messagesNumber_;
    }

    // optional double messages_byte_size = 4;
    public static final int MESSAGES_BYTE_SIZE_FIELD_NUMBER = 4;
    private double messagesByteSize_;
    /**
     * <code>optional double messages_byte_size = 4;</code>
     */
    public boolean hasMessagesByteSize() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double messages_byte_size = 4;</code>
     */
    public double getMessagesByteSize() {
      return messagesByteSize_;
    }

    // optional bool is_internal_msg = 5 [default = false];
    public static final int IS_INTERNAL_MSG_FIELD_NUMBER = 5;
    private boolean isInternalMsg_;
    /**
     * <code>optional bool is_internal_msg = 5 [default = false];</code>
     */
    public boolean hasIsInternalMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool is_internal_msg = 5 [default = false];</code>
     */
    public boolean getIsInternalMsg() {
      return isInternalMsg_;
    }

    private void initFields() {
      workerSourceId_ = 0;
      workerDestId_ = 0;
      messagesNumber_ = 0;
      messagesByteSize_ = 0D;
      isInternalMsg_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWorkerSourceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWorkerDestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, workerSourceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, workerDestId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, messagesNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, messagesByteSize_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isInternalMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, workerSourceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, workerDestId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, messagesNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, messagesByteSize_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isInternalMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protobuf.ExchangedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MessagesProtoBook.ExchangedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagesProtoBook.internal_static_Protobuf_ExchangedMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.MessagesProtoBook.internal_static_Protobuf_ExchangedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
              com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.class, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder.class);
      }

      // Construct using MessagesProtoBook.ExchangedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
//        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        workerSourceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        workerDestId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        messagesNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        messagesByteSize_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        isInternalMsg_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unipg.givip.common.protoutils.MessagesProtoBook.internal_static_Protobuf_ExchangedMessage_descriptor;
      }

      public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage getDefaultInstanceForType() {
        return com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.getDefaultInstance();
      }

      public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage build() {
        com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage buildPartial() {
        com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage result = new com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.workerSourceId_ = workerSourceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.workerDestId_ = workerDestId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.messagesNumber_ = messagesNumber_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.messagesByteSize_ = messagesByteSize_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isInternalMsg_ = isInternalMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage) {
          return mergeFrom((com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage other) {
        if (other == com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.getDefaultInstance()) return this;
        if (other.hasWorkerSourceId()) {
          setWorkerSourceId(other.getWorkerSourceId());
        }
        if (other.hasWorkerDestId()) {
          setWorkerDestId(other.getWorkerDestId());
        }
        if (other.hasMessagesNumber()) {
          setMessagesNumber(other.getMessagesNumber());
        }
        if (other.hasMessagesByteSize()) {
          setMessagesByteSize(other.getMessagesByteSize());
        }
        if (other.hasIsInternalMsg()) {
          setIsInternalMsg(other.getIsInternalMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWorkerSourceId()) {
          
          return false;
        }
        if (!hasWorkerDestId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 worker_source_id = 1;
      private int workerSourceId_ ;
      /**
       * <code>required int32 worker_source_id = 1;</code>
       */
      public boolean hasWorkerSourceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 worker_source_id = 1;</code>
       */
      public int getWorkerSourceId() {
        return workerSourceId_;
      }
      /**
       * <code>required int32 worker_source_id = 1;</code>
       */
      public Builder setWorkerSourceId(int value) {
        bitField0_ |= 0x00000001;
        workerSourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 worker_source_id = 1;</code>
       */
      public Builder clearWorkerSourceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        workerSourceId_ = 0;
        onChanged();
        return this;
      }

      // required int32 worker_dest_id = 2;
      private int workerDestId_ ;
      /**
       * <code>required int32 worker_dest_id = 2;</code>
       */
      public boolean hasWorkerDestId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 worker_dest_id = 2;</code>
       */
      public int getWorkerDestId() {
        return workerDestId_;
      }
      /**
       * <code>required int32 worker_dest_id = 2;</code>
       */
      public Builder setWorkerDestId(int value) {
        bitField0_ |= 0x00000002;
        workerDestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 worker_dest_id = 2;</code>
       */
      public Builder clearWorkerDestId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        workerDestId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 messages_number = 3;
      private int messagesNumber_ ;
      /**
       * <code>optional int32 messages_number = 3;</code>
       */
      public boolean hasMessagesNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 messages_number = 3;</code>
       */
      public int getMessagesNumber() {
        return messagesNumber_;
      }
      /**
       * <code>optional int32 messages_number = 3;</code>
       */
      public Builder setMessagesNumber(int value) {
        bitField0_ |= 0x00000004;
        messagesNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messages_number = 3;</code>
       */
      public Builder clearMessagesNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messagesNumber_ = 0;
        onChanged();
        return this;
      }

      // optional double messages_byte_size = 4;
      private double messagesByteSize_ ;
      /**
       * <code>optional double messages_byte_size = 4;</code>
       */
      public boolean hasMessagesByteSize() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double messages_byte_size = 4;</code>
       */
      public double getMessagesByteSize() {
        return messagesByteSize_;
      }
      /**
       * <code>optional double messages_byte_size = 4;</code>
       */
      public Builder setMessagesByteSize(double value) {
        bitField0_ |= 0x00000008;
        messagesByteSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double messages_byte_size = 4;</code>
       */
      public Builder clearMessagesByteSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messagesByteSize_ = 0D;
        onChanged();
        return this;
      }

      // optional bool is_internal_msg = 5 [default = false];
      private boolean isInternalMsg_ ;
      /**
       * <code>optional bool is_internal_msg = 5 [default = false];</code>
       */
      public boolean hasIsInternalMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool is_internal_msg = 5 [default = false];</code>
       */
      public boolean getIsInternalMsg() {
        return isInternalMsg_;
      }
      /**
       * <code>optional bool is_internal_msg = 5 [default = false];</code>
       */
      public Builder setIsInternalMsg(boolean value) {
        bitField0_ |= 0x00000010;
        isInternalMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_internal_msg = 5 [default = false];</code>
       */
      public Builder clearIsInternalMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isInternalMsg_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Protobuf.ExchangedMessage)
    }

    static {
      defaultInstance = new ExchangedMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Protobuf.ExchangedMessage)
  }

  public interface MessagesBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Protobuf.ExchangedMessage exchange_message = 1;
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    java.util.List<com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage> 
        getExchangeMessageList();
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage getExchangeMessage(int index);
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    int getExchangeMessageCount();
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    java.util.List<? extends com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessageOrBuilder> 
        getExchangeMessageOrBuilderList();
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessageOrBuilder getExchangeMessageOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Protobuf.MessagesBook}
   */
  public static final class MessagesBook extends
      com.google.protobuf.GeneratedMessage
      implements MessagesBookOrBuilder {
    @SuppressWarnings(justification="No bug", value="SE_BAD_FIELD")
    // Use MessagesBook.newBuilder() to construct.
    private MessagesBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessagesBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessagesBook defaultInstance;
    public static MessagesBook getDefaultInstance() {
      return defaultInstance;
    }

    public MessagesBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessagesBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                exchangeMessage_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              exchangeMessage_.add(input.readMessage(com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          exchangeMessage_ = java.util.Collections.unmodifiableList(exchangeMessage_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unipg.givip.common.protoutils.MessagesProtoBook.internal_static_Protobuf_MessagesBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unipg.givip.common.protoutils.MessagesProtoBook.internal_static_Protobuf_MessagesBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook.class, com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook.Builder.class);
    }

    public static final com.google.protobuf.Parser<MessagesBook> PARSER =
        new com.google.protobuf.AbstractParser<MessagesBook>() {
      public MessagesBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessagesBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessagesBook> getParserForType() {
      return PARSER;
    }

    // repeated .Protobuf.ExchangedMessage exchange_message = 1;
    public static final int EXCHANGE_MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage> exchangeMessage_;
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    public java.util.List<com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage> getExchangeMessageList() {
      return exchangeMessage_;
    }
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    public java.util.List<? extends com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessageOrBuilder> 
        getExchangeMessageOrBuilderList() {
      return exchangeMessage_;
    }
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    public int getExchangeMessageCount() {
      return exchangeMessage_.size();
    }
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage getExchangeMessage(int index) {
      return exchangeMessage_.get(index);
    }
    /**
     * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
     */
    public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessageOrBuilder getExchangeMessageOrBuilder(
        int index) {
      return exchangeMessage_.get(index);
    }

    private void initFields() {
      exchangeMessage_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getExchangeMessageCount(); i++) {
        if (!getExchangeMessage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < exchangeMessage_.size(); i++) {
        output.writeMessage(1, exchangeMessage_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < exchangeMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, exchangeMessage_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protobuf.MessagesBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unipg.givip.common.protoutils.MessagesProtoBook.internal_static_Protobuf_MessagesBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.MessagesProtoBook.internal_static_Protobuf_MessagesBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
              com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook.class, com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook.Builder.class);
      }

      // Construct using MessagesProtoBook.MessagesBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExchangeMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (exchangeMessageBuilder_ == null) {
          exchangeMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          exchangeMessageBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unipg.givip.common.protoutils.MessagesProtoBook.internal_static_Protobuf_MessagesBook_descriptor;
      }

      public com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook getDefaultInstanceForType() {
        return com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook.getDefaultInstance();
      }

      public com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook build() {
        com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook buildPartial() {
        com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook result = new com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook(this);
        int from_bitField0_ = bitField0_;
        if (exchangeMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            exchangeMessage_ = java.util.Collections.unmodifiableList(exchangeMessage_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.exchangeMessage_ = exchangeMessage_;
        } else {
          result.exchangeMessage_ = exchangeMessageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook) {
          return mergeFrom((com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook other) {
        if (other == com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook.getDefaultInstance()) return this;
        if (exchangeMessageBuilder_ == null) {
          if (!other.exchangeMessage_.isEmpty()) {
            if (exchangeMessage_.isEmpty()) {
              exchangeMessage_ = other.exchangeMessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureExchangeMessageIsMutable();
              exchangeMessage_.addAll(other.exchangeMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.exchangeMessage_.isEmpty()) {
            if (exchangeMessageBuilder_.isEmpty()) {
              exchangeMessageBuilder_.dispose();
              exchangeMessageBuilder_ = null;
              exchangeMessage_ = other.exchangeMessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
              exchangeMessageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExchangeMessageFieldBuilder() : null;
            } else {
              exchangeMessageBuilder_.addAllMessages(other.exchangeMessage_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getExchangeMessageCount(); i++) {
          if (!getExchangeMessage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unipg.givip.common.protoutils.MessagesProtoBook.MessagesBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Protobuf.ExchangedMessage exchange_message = 1;
      private java.util.List<com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage> exchangeMessage_ =
        java.util.Collections.emptyList();
      private void ensureExchangeMessageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          exchangeMessage_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage>(exchangeMessage_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
      com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessageOrBuilder> exchangeMessageBuilder_;

      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage> getExchangeMessageList() {
        if (exchangeMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exchangeMessage_);
        } else {
          return exchangeMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public int getExchangeMessageCount() {
        if (exchangeMessageBuilder_ == null) {
          return exchangeMessage_.size();
        } else {
          return exchangeMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage getExchangeMessage(int index) {
        if (exchangeMessageBuilder_ == null) {
          return exchangeMessage_.get(index);
        } else {
          return exchangeMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public Builder setExchangeMessage(
          int index, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage value) {
        if (exchangeMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExchangeMessageIsMutable();
          exchangeMessage_.set(index, value);
          onChanged();
        } else {
          exchangeMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public Builder setExchangeMessage(
          int index, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder builderForValue) {
        if (exchangeMessageBuilder_ == null) {
          ensureExchangeMessageIsMutable();
          exchangeMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          exchangeMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public Builder addExchangeMessage(com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage value) {
        if (exchangeMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExchangeMessageIsMutable();
          exchangeMessage_.add(value);
          onChanged();
        } else {
          exchangeMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public Builder addExchangeMessage(
          int index, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage value) {
        if (exchangeMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExchangeMessageIsMutable();
          exchangeMessage_.add(index, value);
          onChanged();
        } else {
          exchangeMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public Builder addExchangeMessage(
        com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder builderForValue) {
        if (exchangeMessageBuilder_ == null) {
          ensureExchangeMessageIsMutable();
          exchangeMessage_.add(builderForValue.build());
          onChanged();
        } else {
          exchangeMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public Builder addExchangeMessage(
          int index, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder builderForValue) {
        if (exchangeMessageBuilder_ == null) {
          ensureExchangeMessageIsMutable();
          exchangeMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          exchangeMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public Builder addAllExchangeMessage(
          java.lang.Iterable<? extends com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage> values) {
        if (exchangeMessageBuilder_ == null) {
          ensureExchangeMessageIsMutable();
          super.addAll(values, exchangeMessage_);
          onChanged();
        } else {
          exchangeMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public Builder clearExchangeMessage() {
        if (exchangeMessageBuilder_ == null) {
          exchangeMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          exchangeMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public Builder removeExchangeMessage(int index) {
        if (exchangeMessageBuilder_ == null) {
          ensureExchangeMessageIsMutable();
          exchangeMessage_.remove(index);
          onChanged();
        } else {
          exchangeMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder getExchangeMessageBuilder(
          int index) {
        return getExchangeMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessageOrBuilder getExchangeMessageOrBuilder(
          int index) {
        if (exchangeMessageBuilder_ == null) {
          return exchangeMessage_.get(index);  } else {
          return exchangeMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public java.util.List<? extends com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessageOrBuilder> 
           getExchangeMessageOrBuilderList() {
        if (exchangeMessageBuilder_ != null) {
          return exchangeMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exchangeMessage_);
        }
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder addExchangeMessageBuilder() {
        return getExchangeMessageFieldBuilder().addBuilder(
          com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder addExchangeMessageBuilder(
          int index) {
        return getExchangeMessageFieldBuilder().addBuilder(
            index, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.ExchangedMessage exchange_message = 1;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder> 
           getExchangeMessageBuilderList() {
        return getExchangeMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
      com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessageOrBuilder> 
          getExchangeMessageFieldBuilder() {
        if (exchangeMessageBuilder_ == null) {
          exchangeMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessage.Builder, com.unipg.givip.common.protoutils.MessagesProtoBook.ExchangedMessageOrBuilder>(
                  exchangeMessage_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          exchangeMessage_ = null;
        }
        return exchangeMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Protobuf.MessagesBook)
    }

    static {
      defaultInstance = new MessagesBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Protobuf.MessagesBook)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_ExchangedMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protobuf_ExchangedMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_MessagesBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protobuf_MessagesBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037MessageProto/messagesbook.proto\022\010Proto" +
      "buf\"\231\001\n\020ExchangedMessage\022\030\n\020worker_sourc" +
      "e_id\030\001 \002(\005\022\026\n\016worker_dest_id\030\002 \002(\005\022\027\n\017me" +
      "ssages_number\030\003 \001(\005\022\032\n\022messages_byte_siz" +
      "e\030\004 \001(\001\022\036\n\017is_internal_msg\030\005 \001(\010:\005false\"" +
      "D\n\014MessagesBook\0224\n\020exchange_message\030\001 \003(" +
      "\0132\032.Protobuf.ExchangedMessageB \n\013com.mes" +
      "sageB\021MessagesProtoBook"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Protobuf_ExchangedMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Protobuf_ExchangedMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protobuf_ExchangedMessage_descriptor,
              new java.lang.String[] { "WorkerSourceId", "WorkerDestId", "MessagesNumber", "MessagesByteSize", "IsInternalMsg", });
          internal_static_Protobuf_MessagesBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Protobuf_MessagesBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protobuf_MessagesBook_descriptor,
              new java.lang.String[] { "ExchangeMessage", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
