// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto/supersteptimestamp.proto

package com.unipg.givip.common.protoutils;

import edu.umd.cs.findbugs.annotations.SuppressWarnings;

public final class SuperstepProtoInfo {
  private SuperstepProtoInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SuperstepOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required sint64 numero = 1;
    /**
     * <code>required sint64 numero = 1;</code>
     */
    boolean hasNumero();
    /**
     * <code>required sint64 numero = 1;</code>
     */
    long getNumero();

    // required double duration = 2;
    /**
     * <code>required double duration = 2;</code>
     */
    boolean hasDuration();
    /**
     * <code>required double duration = 2;</code>
     */
    double getDuration();
  }
  /**
   * Protobuf type {@code Protobuf.Superstep}
   */
  public static final class Superstep extends
      com.google.protobuf.GeneratedMessage
      implements SuperstepOrBuilder {
    @SuppressWarnings(justification="No bug", value="SE_BAD_FIELD")
    // Use Superstep.newBuilder() to construct.
    private Superstep(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Superstep(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Superstep defaultInstance;
    public static Superstep getDefaultInstance() {
      return defaultInstance;
    }

    public Superstep getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Superstep(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              numero_ = input.readSInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              duration_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_Superstep_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_Superstep_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.class, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder.class);
    }

    public static final com.google.protobuf.Parser<Superstep> PARSER =
        new com.google.protobuf.AbstractParser<Superstep>() {
      public Superstep parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Superstep(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Superstep> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required sint64 numero = 1;
    public static final int NUMERO_FIELD_NUMBER = 1;
    private long numero_;
    /**
     * <code>required sint64 numero = 1;</code>
     */
    public boolean hasNumero() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sint64 numero = 1;</code>
     */
    public long getNumero() {
      return numero_;
    }

    // required double duration = 2;
    public static final int DURATION_FIELD_NUMBER = 2;
    private double duration_;
    /**
     * <code>required double duration = 2;</code>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double duration = 2;</code>
     */
    public double getDuration() {
      return duration_;
    }

    private void initFields() {
      numero_ = 0L;
      duration_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNumero()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDuration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt64(1, numero_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, duration_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, numero_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, duration_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protobuf.Superstep}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_Superstep_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_Superstep_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.class, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder.class);
      }

      // Construct using org.apache.giraph.master.SuperstepProtoInfo.Superstep.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
//        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        numero_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        duration_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_Superstep_descriptor;
      }

      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep getDefaultInstanceForType() {
        return com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.getDefaultInstance();
      }

      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep build() {
        com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep buildPartial() {
        com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep result = new com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.numero_ = numero_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.duration_ = duration_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep) {
          return mergeFrom((com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep other) {
        if (other == com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.getDefaultInstance()) return this;
        if (other.hasNumero()) {
          setNumero(other.getNumero());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNumero()) {
          
          return false;
        }
        if (!hasDuration()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required sint64 numero = 1;
      private long numero_ ;
      /**
       * <code>required sint64 numero = 1;</code>
       */
      public boolean hasNumero() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sint64 numero = 1;</code>
       */
      public long getNumero() {
        return numero_;
      }
      /**
       * <code>required sint64 numero = 1;</code>
       */
      public Builder setNumero(long value) {
        bitField0_ |= 0x00000001;
        numero_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint64 numero = 1;</code>
       */
      public Builder clearNumero() {
        bitField0_ = (bitField0_ & ~0x00000001);
        numero_ = 0L;
        onChanged();
        return this;
      }

      // required double duration = 2;
      private double duration_ ;
      /**
       * <code>required double duration = 2;</code>
       */
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double duration = 2;</code>
       */
      public double getDuration() {
        return duration_;
      }
      /**
       * <code>required double duration = 2;</code>
       */
      public Builder setDuration(double value) {
        bitField0_ |= 0x00000002;
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double duration = 2;</code>
       */
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000002);
        duration_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Protobuf.Superstep)
    }

    static {
      defaultInstance = new Superstep(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Protobuf.Superstep)
  }

  public interface SuperstepsInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Protobuf.Superstep superstep = 1;
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    java.util.List<com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep> 
        getSuperstepList();
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep getSuperstep(int index);
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    int getSuperstepCount();
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    java.util.List<? extends com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder> 
        getSuperstepOrBuilderList();
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder getSuperstepOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Protobuf.SuperstepsInfo}
   */
  public static final class SuperstepsInfo extends
      com.google.protobuf.GeneratedMessage
      implements SuperstepsInfoOrBuilder {
    @SuppressWarnings(justification="No bug", value="SE_BAD_FIELD")
    // Use SuperstepsInfo.newBuilder() to construct.
    private SuperstepsInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SuperstepsInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SuperstepsInfo defaultInstance;
    public static SuperstepsInfo getDefaultInstance() {
      return defaultInstance;
    }

    public SuperstepsInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SuperstepsInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                superstep_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep>();
                mutable_bitField0_ |= 0x00000001;
              }
              superstep_.add(input.readMessage(com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          superstep_ = java.util.Collections.unmodifiableList(superstep_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_SuperstepsInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_SuperstepsInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo.class, com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo.Builder.class);
    }

    public static final com.google.protobuf.Parser<SuperstepsInfo> PARSER =
        new com.google.protobuf.AbstractParser<SuperstepsInfo>() {
      public SuperstepsInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SuperstepsInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SuperstepsInfo> getParserForType() {
      return PARSER;
    }

    // repeated .Protobuf.Superstep superstep = 1;
    public static final int SUPERSTEP_FIELD_NUMBER = 1;
    private java.util.List<com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep> superstep_;
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    public java.util.List<com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep> getSuperstepList() {
      return superstep_;
    }
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    public java.util.List<? extends com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder> 
        getSuperstepOrBuilderList() {
      return superstep_;
    }
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    public int getSuperstepCount() {
      return superstep_.size();
    }
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    public com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep getSuperstep(int index) {
      return superstep_.get(index);
    }
    /**
     * <code>repeated .Protobuf.Superstep superstep = 1;</code>
     */
    public com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder getSuperstepOrBuilder(
        int index) {
      return superstep_.get(index);
    }

    private void initFields() {
      superstep_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getSuperstepCount(); i++) {
        if (!getSuperstep(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < superstep_.size(); i++) {
        output.writeMessage(1, superstep_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < superstep_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, superstep_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protobuf.SuperstepsInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_SuperstepsInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_SuperstepsInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo.class, com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo.Builder.class);
      }

      // Construct using org.apache.giraph.master.SuperstepProtoInfo.SuperstepsInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSuperstepFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (superstepBuilder_ == null) {
          superstep_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          superstepBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unipg.givip.common.protoutils.SuperstepProtoInfo.internal_static_Protobuf_SuperstepsInfo_descriptor;
      }

      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo getDefaultInstanceForType() {
        return com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo.getDefaultInstance();
      }

      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo build() {
        com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo buildPartial() {
        com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo result = new com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo(this);
        int from_bitField0_ = bitField0_;
        if (superstepBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            superstep_ = java.util.Collections.unmodifiableList(superstep_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.superstep_ = superstep_;
        } else {
          result.superstep_ = superstepBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo) {
          return mergeFrom((com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo other) {
        if (other == com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo.getDefaultInstance()) return this;
        if (superstepBuilder_ == null) {
          if (!other.superstep_.isEmpty()) {
            if (superstep_.isEmpty()) {
              superstep_ = other.superstep_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSuperstepIsMutable();
              superstep_.addAll(other.superstep_);
            }
            onChanged();
          }
        } else {
          if (!other.superstep_.isEmpty()) {
            if (superstepBuilder_.isEmpty()) {
              superstepBuilder_.dispose();
              superstepBuilder_ = null;
              superstep_ = other.superstep_;
              bitField0_ = (bitField0_ & ~0x00000001);
              superstepBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSuperstepFieldBuilder() : null;
            } else {
              superstepBuilder_.addAllMessages(other.superstep_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSuperstepCount(); i++) {
          if (!getSuperstep(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepsInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Protobuf.Superstep superstep = 1;
      private java.util.List<com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep> superstep_ =
        java.util.Collections.emptyList();
      private void ensureSuperstepIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          superstep_ = new java.util.ArrayList<com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep>(superstep_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder, com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder> superstepBuilder_;

      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep> getSuperstepList() {
        if (superstepBuilder_ == null) {
          return java.util.Collections.unmodifiableList(superstep_);
        } else {
          return superstepBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public int getSuperstepCount() {
        if (superstepBuilder_ == null) {
          return superstep_.size();
        } else {
          return superstepBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep getSuperstep(int index) {
        if (superstepBuilder_ == null) {
          return superstep_.get(index);
        } else {
          return superstepBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public Builder setSuperstep(
          int index, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep value) {
        if (superstepBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuperstepIsMutable();
          superstep_.set(index, value);
          onChanged();
        } else {
          superstepBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public Builder setSuperstep(
          int index, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder builderForValue) {
        if (superstepBuilder_ == null) {
          ensureSuperstepIsMutable();
          superstep_.set(index, builderForValue.build());
          onChanged();
        } else {
          superstepBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public Builder addSuperstep(com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep value) {
        if (superstepBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuperstepIsMutable();
          superstep_.add(value);
          onChanged();
        } else {
          superstepBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public Builder addSuperstep(
          int index, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep value) {
        if (superstepBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuperstepIsMutable();
          superstep_.add(index, value);
          onChanged();
        } else {
          superstepBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public Builder addSuperstep(
          com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder builderForValue) {
        if (superstepBuilder_ == null) {
          ensureSuperstepIsMutable();
          superstep_.add(builderForValue.build());
          onChanged();
        } else {
          superstepBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public Builder addSuperstep(
          int index, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder builderForValue) {
        if (superstepBuilder_ == null) {
          ensureSuperstepIsMutable();
          superstep_.add(index, builderForValue.build());
          onChanged();
        } else {
          superstepBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public Builder addAllSuperstep(
          java.lang.Iterable<? extends com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep> values) {
        if (superstepBuilder_ == null) {
          ensureSuperstepIsMutable();
          super.addAll(values, superstep_);
          onChanged();
        } else {
          superstepBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public Builder clearSuperstep() {
        if (superstepBuilder_ == null) {
          superstep_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          superstepBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public Builder removeSuperstep(int index) {
        if (superstepBuilder_ == null) {
          ensureSuperstepIsMutable();
          superstep_.remove(index);
          onChanged();
        } else {
          superstepBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder getSuperstepBuilder(
          int index) {
        return getSuperstepFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder getSuperstepOrBuilder(
          int index) {
        if (superstepBuilder_ == null) {
          return superstep_.get(index);  } else {
          return superstepBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public java.util.List<? extends com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder> 
           getSuperstepOrBuilderList() {
        if (superstepBuilder_ != null) {
          return superstepBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(superstep_);
        }
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder addSuperstepBuilder() {
        return getSuperstepFieldBuilder().addBuilder(
            com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder addSuperstepBuilder(
          int index) {
        return getSuperstepFieldBuilder().addBuilder(
            index, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.getDefaultInstance());
      }
      /**
       * <code>repeated .Protobuf.Superstep superstep = 1;</code>
       */
      public java.util.List<com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder> 
           getSuperstepBuilderList() {
        return getSuperstepFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder, com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder> 
          getSuperstepFieldBuilder() {
        if (superstepBuilder_ == null) {
          superstepBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep, com.unipg.givip.common.protoutils.SuperstepProtoInfo.Superstep.Builder, com.unipg.givip.common.protoutils.SuperstepProtoInfo.SuperstepOrBuilder>(
                  superstep_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          superstep_ = null;
        }
        return superstepBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Protobuf.SuperstepsInfo)
    }

    static {
      defaultInstance = new SuperstepsInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Protobuf.SuperstepsInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_Superstep_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protobuf_Superstep_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_SuperstepsInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protobuf_SuperstepsInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%MessageProto/supersteptimestamp.proto\022" +
      "\010Protobuf\"-\n\tSuperstep\022\016\n\006numero\030\001 \002(\022\022\020" +
      "\n\010duration\030\002 \002(\001\"8\n\016SuperstepsInfo\022&\n\tsu" +
      "perstep\030\001 \003(\0132\023.Protobuf.SuperstepB!\n\013co" +
      "m.messageB\022SuperstepProtoInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Protobuf_Superstep_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Protobuf_Superstep_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protobuf_Superstep_descriptor,
              new java.lang.String[] { "Numero", "Duration", });
          internal_static_Protobuf_SuperstepsInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Protobuf_SuperstepsInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protobuf_SuperstepsInfo_descriptor,
              new java.lang.String[] { "Superstep", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
